package com.todolist.dto;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

/**
 * View DTO for reminder notifications generated by notification strategies.
 */
public class ReminderNotification {

    private final Long taskId;
    private final String taskTitle;
    private final LocalDate taskDate;
    private final LocalTime taskTime;
    private final LocalDateTime triggerAt;
    private final String type;
    private final String message;
    private final String statusLabel;
    private final String statusCssClass;
    private final boolean active;

    public ReminderNotification(Long taskId, String taskTitle, LocalDate taskDate, LocalTime taskTime,
                                LocalDateTime triggerAt, String type, String message,
                                String statusLabel, String statusCssClass, boolean active) {
        this.taskId = taskId;
        this.taskTitle = taskTitle;
        this.taskDate = taskDate;
        this.taskTime = taskTime;
        this.triggerAt = triggerAt;
        this.type = type;
        this.message = message;
        this.statusLabel = statusLabel;
        this.statusCssClass = statusCssClass;
        this.active = active;
    }

    public Long getTaskId() {
        return taskId;
    }

    public String getTaskTitle() {
        return taskTitle;
    }

    public LocalDate getTaskDate() {
        return taskDate;
    }

    public LocalTime getTaskTime() {
        return taskTime;
    }

    public LocalDateTime getTriggerAt() {
        return triggerAt;
    }

    public String getType() {
        return type;
    }

    public String getMessage() {
        return message;
    }

    public String getStatusLabel() {
        return statusLabel;
    }

    public String getStatusCssClass() {
        return statusCssClass;
    }

    public boolean isActive() {
        return active;
    }
}
