spring:
  application:
    name: TaskFlow

  datasource:
    url: jdbc:mysql://127.0.0.1:3307/todolist_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    encoding: UTF-8

logging:
  level:
    root: INFO
    com.todolist: DEBUG
